main_page/urls.py
from django.urls import path

from . import views


app_name = 'main_page'
urlpatterns = [
    path('', views.index, name='index'),
]

mysite/urls.py
import debug_toolbar
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView

urlpatterns = [
    path('accueil/', include('main_page.urls')),
    path('velouse/', include('velouse.urls')),
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='velouse/')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('__debug__/', include(debug_toolbar.urls)),
]

velouse/urls.py
from django.urls import path

from . import views

app_name = 'velouse'
urlpatterns = [
    path('', views.index, name='index'),
    path('update', views.update, name='update'),
    path('<int:station_number>/star', views.star, name='star'),
    path('<int:station_number>', views.detail, name='detail'),
    path('set_default_view', views.set_default_view, name='set_view')
]

main_page/models.py
from django.db import models

# Create your models here.

main_page/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'main_page/index.html')

main_page/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Oh le joli petit site{% endblock %}</title>
    {% block includes %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'velouse/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'velouse/style.css' %}">
    <script src="{% static 'velouse/jquery.min.js' %}"></script>
    <script src="{% static 'velouse/bootstrap.min.js' %}"></script>
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css"
          integrity="sha512-xodZBNTC5n17Xt2atTPuE1HxjVMSvLVW9ocqUKLsCC5CXdbqCmblAshOMAS6/keqq/sMZMZ19scR4PsZChSR7A=="
          crossorigin=""/>
    <script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"
            integrity="sha512-XQoYMqMTK8LvdxXYG3nZ448hOEQiglfqkJs1NOQV44cWnUrBc8PkAOcXy20w0vlaXaVUearIOBhiXZ5V3ynxwA=="
            crossorigin=""></script>
    {% endblock %}
</head>
<body>
{% block header %}
<div class="d-flex justify-content-between bg-secondary p-1 bg-info text-light">
    <a role="button" class="btn" href="{% url 'velouse:index' %}">
        <h1 class="p-2 m-2 flex-grow-1 text-light">T'es chez moi
        {% if user.is_authenticated %}
            {{ user.get_username }} !
        {% endif %}
        </h1>
    </a>
    <div class="button-group mx-2 my-4 ">
        <a role="button" class="btn btn-light p-2" href="{% url 'velouse:index' %}">
            <span class="align-bottom">Rafraichir la page</span>
        </a>
        {% if user.is_staff %}
        <button type="button" class="btn btn-light p-2" data-toggle="modal" data-target="#myModal">
            Mettre à jour la base de données
        </button>
        <div class="modal" id="myModal">
            <div class="modal-dialog">
                <div class="modal-content">
                    <!-- Modal Header -->
                    <div class="modal-header">
                        <h4 class="modal-title text-dark">Recharger toute la base de données</h4>
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                    </div>
                    <!-- Modal body -->
                    <div class="modal-body text-dark">
                        <p>Etes-vous sûr de vouloir recharger toute la base de données ?</p>
                        <p>Cette opération peut durer jusqu'à 50s.</p>
                    </div>
                    <!-- Modal footer -->
                    <div class="modal-footer">
                        <a role="button" class="btn btn-primary" href="{% url 'velouse:update' %}">Confirmer</a>
                        <button type="button" class="btn btn-danger" data-dismiss="modal">Fermer</button>
                    </div>
                </div>
            </div>
        </div>
        {% endif %}
        {% if user.is_authenticated %}
            <a role="button" class="btn btn-secondary p-2 ml-3" href="{% url 'logout'%}?next={{request.path}}">Se déconnecter</a></li>
        {% else %}
            <a role="button" class="btn btn-danger p-2 ml-3" href="{% url 'login'%}?next={{request.path}}">Connexion</a></li>
        {% endif %}
    </div>
</div>
<br>
{% endblock %}
<div class="container">
{% block content %}
{% endblock %}
</div>
</body>
</html>