mysite/urls.py
import debug_toolbar
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView

urlpatterns = [
    path('accueil/', include('main_page.urls')),
    path('velouse/', include('velouse.urls')),
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='velouse/')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('__debug__/', include(debug_toolbar.urls)),
]

velose/urls.py
from django.urls import path

from . import views

app_name = 'velose'
urlpatterns = [
    path('', views.index, name='index'),
    path('update', views.update, name='update'),
    path('star', views.star_no_arg, name='star_no_arg'),
    path('<int:station_number>/star', views.star, name='star'),
    path('<int:station_number>', views.detail, name='detail'),
]

velose/views.py
import json
import re
from datetime import datetime

import requests
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from .models import Station

BASE_URL = 'https://api.jcdecaux.com/vls/v1/stations/'
CONTRACT = 'toulouse'
API_KEY = '54b6f2be9a8f6d369691075425d0e11b4611a9d5'


def index(request):
    starred_stations = Station.objects.filter(starred__exact=True)
    refresh_database()

    context = {'starred_stations': starred_stations, 'stations': Station.objects.all(), }

    return render(request, 'velose/index.html', context)


def refresh_station(station_nb):
    station_url = f'{BASE_URL}{station_nb}?contract={CONTRACT}&apiKey={API_KEY}'
    json_station = json.loads(requests.get(station_url).text)
    db_station = Station.objects.get(number=station_nb)
    db_station.refresh(bike_stands=json_station.get('bike_stands'),
                       available_bike_stands=json_station.get('available_bike_stands'),
                       available_bikes=json_station.get('available_bikes'),
                       status=json_station.get('status'),
                       last_update=json_station.get('last_update'),
                       )
    db_station.save()


def update(request):
    reload_full_database()
    return HttpResponseRedirect(reverse('velose:index'))


def get_stations_from_api():
    print(f'[{datetime.now()}] Request JCDecaux API')
    stations_url = f'{BASE_URL}?contract={CONTRACT}&apiKey={API_KEY}'
    req = requests.get(stations_url)
    return json.loads(req.text)


def reload_full_database():
    print(f'[{datetime.now()}] Start updating station database')
    print(f'[{datetime.now()}] Delete current database')
    Station.objects.all().delete()
    json_stations = get_stations_from_api()
    print(f'[{datetime.now()}] Create station list')
    station_list = []
    for station in json_stations:
        new_name = modify_name(station.get('name'))
        db_station = Station.create(
            number=station.get('number'),
            contract_name=station.get('contract_name'),
            name=new_name,
            address=station.get('address'),
            position=station.get('position'),
            banking=station.get('banking'),
            bonus=station.get('bonus'),
            bike_stands=station.get('bike_stands'),
            available_bike_stands=station.get('available_bike_stands'),
            available_bikes=station.get('available_bikes'),
            status=station.get('status'),
            last_update=station.get('last_update')
        )
        station_list.append(db_station)

    print(f'[{datetime.now()}] Start bulk create')
    Station.objects.bulk_create(station_list)
    print(f'[{datetime.now()}] Database updated')


def refresh_database():
    print(f'[{datetime.now()}] Start refreshing station database')
    stations = get_stations_from_api()
    station_list = []
    for station in stations:
        database_station = Station.objects.get(number=station.get('number'))
        database_station.refresh(bike_stands=station.get('bike_stands'),
                                 available_bike_stands=station.get('available_bike_stands'),
                                 available_bikes=station.get('available_bikes'),
                                 status=station.get('status'),
                                 last_update=station.get('last_update'))
        station_list.append(database_station)

    Station.objects.bulk_update(station_list,
                                fields=['bike_stands', 'available_bike_stands', 'available_bikes', 'status',
                                        'last_update'])


def modify_name(name):
    p = re.compile("\d+ - ([\S\s]*)")
    return p.match(name).group(1).strip()


def star_no_arg(request):
    if request.POST:
        station_number = request.POST.get('station')
    return star(request, station_number)


def star(request, station_number):
    station = Station.objects.get(number=station_number)
    station.toggle_star()
    station.save()
    return HttpResponseRedirect(reverse('velose:index'))


def detail(request, station_number):
    refresh_station(station_number)
    context = {'station': Station.objects.get(number=station_number)}
    return render(request, 'velose/detail.html', context)

velose/templates/velose/detail.html
{% extends "velose/base.html" %}

{% block title %}Station {{ station.number }} - {{ station.name }}{% endblock %}

{% block includes %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'velose/bootstrap.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'velose/style.css' %}">
<script src="{% static 'velose/jquery.min.js' %}"></script>
<script src="{% static 'velose/bootstrap.bundle.min.js' %}"></script>
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css"
   integrity="sha512-xodZBNTC5n17Xt2atTPuE1HxjVMSvLVW9ocqUKLsCC5CXdbqCmblAshOMAS6/keqq/sMZMZ19scR4PsZChSR7A=="
   crossorigin=""/>
<script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"
   integrity="sha512-XQoYMqMTK8LvdxXYG3nZ448hOEQiglfqkJs1NOQV44cWnUrBc8PkAOcXy20w0vlaXaVUearIOBhiXZ5V3ynxwA=="
   crossorigin=""></script>
{% endblock %}

{% block content %}
<div class="d-flex justify-content-between bg-secondary p-1 bg-info text-light">
    <a role="button" class="btn" href="{% url 'velose:index' %}">
        <h1 class="p-2 m-2 flex-grow-1 text-light">Enlarge your vélouse</h1>
    </a>
    <div class="button-group mx-2 my-4 ">
        <a role="button" class="btn btn-light p-2" href="{% url 'velose:detail' station.number %}">
            <span class="align-bottom">Rafraichir les infos de la station</span>
        </a>
    </div>
</div>
<br>
<div class="container">
<div class="station">
    <h1>Station n° {{ station.number }} - {{ station.name }}</h1>
    <ul class="list-group">
        <li class="list-group-item"><span class="font-weight-bold">Station favorite : </span>
            {% if station.starred %}
                Oui
            {% else %}
                Non
            {% endif %}</li>
        <li class="list-group-item"><span class="font-weight-bold">Adresse : </span>{{ station.address }}</li>
        <li class="list-group-item"><span class="font-weight-bold">Nombre de bornes : </span>{{ station.bike_stands }}</li>
        <li class="list-group-item"><span class="font-weight-bold">Vélouses dispos : </span>{{ station.available_bikes }}</li>
        <li class="list-group-item"><span class="font-weight-bold">Bornes libres : </span>{{ station.available_bike_stands }}</li>
        <li class="list-group-item"><span class="font-weight-bold">Etat : </span>
            {% if station.status == 'OPEN' %}
                Ouverte
            {% else %}
                Fermée
            {% endif %}</li>
        <li class="list-group-item">
             <span class="font-weight-bold">Dernière mise-à-jour : </span>
             {{ station.last_update|date:"d/m/Y" }} {{ station.last_update|time:"H:i:s" }}</li>
        <li class="list-group-item"><span class="font-weight-bold">Position : </span>
            <ul class="list-group list-group-flush">
                <li class="list-group-item"><em>Latitude :</em> {{ station.position.lat }}</li>
            <li class="list-group-item"><em>Longitude :</em> {{ station.position.lng }}</li>
            </ul>
        </li>
        <li class="list-group-item"><span class="font-weight-bold">Paiement par carte bancaire : </span>
            {% if station.banking %}
                Accepté
            {% else %}
                Refusé
            {% endif %}
        </li>
         <li class="list-group-item"><span class="font-weight-bold">Bonus : </span>
            {% if station.bonus %}
                Oui
            {% else %}
                Non
            {% endif %}
        </li>
    </ul>
</div>
</div>
{% endblock %}