mysite/urls.py
import debug_toolbar
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView

urlpatterns = [
    path('accueil/', include('main_page.urls')),
    path('velouse/', include('velouse.urls')),
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='velouse/')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('__debug__/', include(debug_toolbar.urls)),
]

velouse/urls.py
from django.urls import path

from . import views

app_name = 'velouse'
urlpatterns = [
    path('', views.index, name='index'),
    path('update', views.update, name='update'),
    path('<int:station_number>/star', views.star, name='star'),
    path('<int:station_number>', views.detail, name='detail'),
    path('set_default_view', views.set_default_view, name='set_view')
]

velouse/models.py
import logging
from datetime import datetime

from django.db import models
from django.dispatch import receiver
from django.utils.timezone import make_aware
from django.conf import settings
from django.contrib.auth.models import AbstractUser

logger = logging.getLogger(__name__)

STATION_STATUSES = (("OPEN", "Open"), ("CLOSED", "Closed"))


class Position(models.Model):
    lat = models.DecimalField(
        max_digits=17,
        decimal_places=14,
        default=settings.DEFAULT_LATITUDE,
    )
    lng = models.DecimalField(
        max_digits=17,
        decimal_places=14,
        default=settings.DEFAULT_LONGITUDE,
    )

    def __str__(self):
        return f"[lat: {self.lat}, lng: {self.lng}]"

    @classmethod
    def create(cls, lat, lng):
        return cls(lat=lat, lng=lng)


class Station(models.Model):
    number = models.IntegerField(primary_key=True)
    contract_name = models.CharField(max_length=50)
    name = models.CharField(
        "nom",
        max_length=200,
    )
    address = models.CharField(
        "adresse",
        max_length=200,
    )
    position = models.OneToOneField(
        "position",
        on_delete=models.CASCADE,
        null=True,
    )
    banking = models.BooleanField()
    bonus = models.BooleanField()
    bike_stands = models.IntegerField("bornes")
    available_bike_stands = models.IntegerField("bornes dispos")
    available_bikes = models.IntegerField("velos dispos")
    status = models.CharField(
        max_length=200,
        choices=STATION_STATUSES,
    )
    last_update = models.DateTimeField("dernière mise-à-jour")

    def __str__(self):
        return f"{self.number} - {self.name}"

    @classmethod
    def create(
        cls,
        number,
        contract_name,
        name,
        address,
        position,
        banking,
        bonus,
        bike_stands,
        available_bike_stands,
        available_bikes,
        status,
        last_update,
    ):
        position_do = Position.create(position.get("lat"), position.get("lng"))
        position_do.save()
        formatted_update = make_aware(datetime.fromtimestamp(last_update / 1000))
        station = cls(
            number=number,
            contract_name=contract_name,
            name=name,
            address=address,
            position=position_do,
            banking=banking,
            bonus=bonus,
            bike_stands=bike_stands,
            available_bike_stands=available_bike_stands,
            available_bikes=available_bikes,
            status=status,
            last_update=formatted_update,
        )
        return station

    def refresh(
        self, bike_stands, available_bike_stands, available_bikes, status, last_update
    ):
        formatted_update = make_aware(datetime.fromtimestamp(last_update / 1000))
        self.bike_stands = bike_stands
        self.available_bike_stands = available_bike_stands
        self.available_bikes = available_bikes
        self.status = status
        self.last_update = formatted_update


class VelouseUser(AbstractUser):
    stations = models.ManyToManyField(
        Station,
        blank=True,
    )
    map_zoom = models.IntegerField(
        "zoom par défaut",
        blank=True,
        default=settings.DEFAULT_ZOOM,
    )
    map_center = models.ForeignKey(
        Position,
        on_delete=models.CASCADE,
        null=True,
        blank=True,
    )

    def toggle_station(self, station):
        if station in self.stations.all():
            logger.info(f'Unstar station "{station}" for user {self.username}')
            self.stations.remove(station)
        else:
            logger.info(f'Star station "{station}" for user {self.username}')
            self.stations.add(station)

    def set_map_view(self, zoom, lat, lng):
        map_center, creation = Position.objects.get_or_create(lat=lat, lng=lng)
        logger.info(
            f"Set default map viem to {map_center} at zoom {zoom} for user {self.username}"
        )
        self.map_center = map_center
        self.map_zoom = zoom


@receiver(models.signals.post_save, sender=VelouseUser)
def user_created(sender, instance, created, **kwargs):
    if created and not instance.map_center:
        pos, creation = Position.objects.get_or_create(
            lat=settings.DEFAULT_LATITUDE, lng=settings.DEFAULT_LONGITUDE
        )
        instance.map_center = pos
        instance.save()

velouse/forms.py
from django import forms
from django.conf import settings

LABEL_SUFFIX = ''


class MapSizeForm(forms.Form):
    lat = forms.FloatField(required=True,
                           initial=settings.DEFAULT_LATITUDE,
                           label='Latitude',
                           label_suffix=LABEL_SUFFIX,
                           widget=forms.TextInput(attrs={'class': 'form-control'}),
                           )
    lng = forms.FloatField(required=True,
                           initial=settings.DEFAULT_LONGITUDE,
                           label='Longitude',
                           label_suffix=LABEL_SUFFIX,
                           widget=forms.TextInput(attrs={'class': 'form-control'}),
                           )
    zoom = forms.IntegerField(required=False,
                              initial=settings.DEFAULT_ZOOM,
                              label='Zoom',
                              label_suffix=LABEL_SUFFIX,
                              widget=forms.TextInput(attrs={'class': 'form-control'}),
                              )

velouse/views.py
import logging

from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from .models import Station
from .forms import MapSizeForm
from .database_operations import refresh_database, reload_full_database, refresh

logger = logging.getLogger(__name__)


def index(request):
    logger.info("Loading main Velouse page")
    refresh_database()

    user = request.user
    if user.is_authenticated:
        form = MapSizeForm(
            initial={
                "lat": user.map_center.lat,
                "lng": user.map_center.lng,
                "zoom": user.map_zoom,
            }
        )
    else:
        form = MapSizeForm()

    context = {
        "stations": Station.objects.select_related("position").all(),
        "form": form,
    }
    return render(request, "velouse/index.html", context)


def update(request):
    reload_full_database()
    return HttpResponseRedirect(reverse("velouse:index"))


def set_default_view(request):
    user = request.user
    if user.is_authenticated:
        if request.method == "POST":
            form = MapSizeForm(request.POST)
            if form.is_valid():
                lat = form.cleaned_data["lat"]
                lng = form.cleaned_data["lng"]
                zoom = form.cleaned_data["zoom"]
                logger.info(
                    f"Set default view of {user.get_username()} to latitude {lat}, longitude {lng} and zoom {zoom}"
                )
                user.set_map_view(zoom, lat, lng)
                user.save()
                return HttpResponseRedirect(reverse("velouse:index"))
        else:
            form = MapSizeForm()
    return HttpResponseRedirect(reverse("velouse:index"))


def star(request, station_number):
    station = Station.objects.get(number=station_number)
    user = request.user
    if user.is_authenticated:
        user.toggle_station(station)
        user.save()
    return HttpResponseRedirect(reverse("velouse:index"))


def detail(request, station_number):
    station = Station.objects.get(number=station_number)
    logger.info(f'Loading information page for station "{station}"')
    refresh(station)
    context = {"station": station}
    return render(request, "velouse/detail.html", context)

velouse/templates/velouse/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Oh le joli petit site{% endblock %}</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'velouse/css/bootstrap.min.css' %}">
    <script src="{% static 'velouse/js/jquery.min.js' %}"></script>
    <script src="{% static 'velouse/js/bootstrap.bundle.min.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'velouse/css/style.css' %}">
    <link rel="icon" href="{% static 'velouse/img/velouse.ico' %}" />
    {% block includes %}
    {% endblock %}
</head>
<body>
{% block header %}
<div class="d-flex justify-content-between bg-secondary p-1 bg-info text-light">
    <a role="button" class="btn" href="{% url 'velouse:index' %}">
        <h1 class="p-2 m-2 flex-grow-1 text-light">Enlarge your vélouse
        {% if user.is_authenticated %}
         - {{ user.get_username }}
        {% endif %}
        </h1>
    </a>
    <div class="button-group mx-2 my-4 ">
        <a role="button" class="btn btn-light p-2" href="{% url 'velouse:index' %}">
            <span class="align-bottom">Rafraichir la page</span>
        </a>
        {% if user.is_staff %}
        <button type="button" class="btn btn-light p-2" data-toggle="modal" data-target="#myModal">
            Mettre à jour la base de données
        </button>
        <div class="modal" id="myModal">
            <div class="modal-dialog">
                <div class="modal-content">
                    <!-- Modal Header -->
                    <div class="modal-header">
                        <h4 class="modal-title text-dark">Recharger toute la base de données</h4>
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                    </div>
                    <!-- Modal body -->
                    <div class="modal-body text-dark">
                        <p>Etes-vous sûr de vouloir recharger toute la base de données ?</p>
                        <p>Cette opération peut durer jusqu'à 50s.</p>
                    </div>
                    <!-- Modal footer -->
                    <div class="modal-footer">
                        <a role="button" class="btn btn-primary" href="{% url 'velouse:update' %}">Confirmer</a>
                        <button type="button" class="btn btn-danger" data-dismiss="modal">Fermer</button>
                    </div>
                </div>
            </div>
        </div>
        {% endif %}
        {% if user.is_authenticated %}
            <a role="button" class="btn btn-secondary p-2 ml-3" href="{% url 'logout'%}?next={{request.path}}">Se déconnecter</a>
        {% else %}
            <a role="button" class="btn btn-danger p-2 ml-3" href="{% url 'login'%}?next={{request.path}}">Connexion</a>
        {% endif %}
    </div>
</div>
<br>
{% endblock %}
<div class="container">
{% block content %}
{% endblock %}
</div>
</body>
</html>

velouse/templates/velouse/detail.html
{% extends "velouse/base.html" %}

{% block title %}Station {{ station.number }} - {{ station.name }}{% endblock %}

{% block content %}
{% with starred=user.stations.all %}
<div class="container">
<div class="station">
    <h1>Station n° {{ station.number }} - {{ station.name }}
    {% if station in starred %}
                <a href="{% url 'velouse:star' station.number %}" type="button" class="btn btn-white text-warning pt-0 pb-2 px-0 mx-2 my-0" style="overflow: visible">
                <svg width="2em" height="1.8em" viewBox="0 0 16 16" class="bi bi-star-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd" d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.283.95l-3.523 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z"/>
                </svg>
                </a>
            {% else %}
                <a href="{% url 'velouse:star' station.number %}" type="button" class="btn btn-white text-warning pt-0 pb-2 px-0 mx-2 my-0" style="overflow: visible">
                <svg width="2em" height="1.8em" viewBox="0 0 16 16" class="bi bi-star" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd" d="M2.866 14.85c-.078.444.36.791.746.593l4.39-2.256 4.389 2.256c.386.198.824-.149.746-.592l-.83-4.73 3.523-3.356c.329-.314.158-.888-.283-.95l-4.898-.696L8.465.792a.513.513 0 0 0-.927 0L5.354 5.12l-4.898.696c-.441.062-.612.636-.283.95l3.523 3.356-.83 4.73zm4.905-2.767l-3.686 1.894.694-3.957a.565.565 0 0 0-.163-.505L1.71 6.745l4.052-.576a.525.525 0 0 0 .393-.288l1.847-3.658 1.846 3.658a.525.525 0 0 0 .393.288l4.052.575-2.906 2.77a.564.564 0 0 0-.163.506l.694 3.957-3.686-1.894a.503.503 0 0 0-.461 0z"/>
                </svg>
                </a>
            {% endif %}</h1>
    <ul class="list-group">
        <li class="list-group-item"><span class="font-weight-bold">Station favorite : </span>
            {% if station in starred %}
                Oui
            {% else %}
                Non
            {% endif %}</li>
        <li class="list-group-item"><span class="font-weight-bold">Adresse : </span>{{ station.address }}</li>
        <li class="list-group-item"><span class="font-weight-bold">Nombre de bornes : </span>{{ station.bike_stands }}</li>
        <li class="list-group-item"><span class="font-weight-bold">Vélouses dispos : </span>{{ station.available_bikes }}</li>
        <li class="list-group-item"><span class="font-weight-bold">Bornes libres : </span>{{ station.available_bike_stands }}</li>
        <li class="list-group-item"><span class="font-weight-bold">Etat : </span>
            {% if station.status == 'OPEN' %}
                Ouverte
            {% else %}
                Fermée
            {% endif %}</li>
        <li class="list-group-item">
             <span class="font-weight-bold">Dernière mise-à-jour : </span>
             {{ station.last_update|date:"d/m/Y" }} {{ station.last_update|time:"H:i:s" }}</li>
        <li class="list-group-item"><span class="font-weight-bold">Position : </span>
            <ul class="list-group list-group-flush">
                <li class="list-group-item"><em>Latitude :</em> {{ station.position.lat }}</li>
            <li class="list-group-item"><em>Longitude :</em> {{ station.position.lng }}</li>
            </ul>
        </li>
        <li class="list-group-item"><span class="font-weight-bold">Paiement par carte bancaire : </span>
            {% if station.banking %}
                Accepté
            {% else %}
                Refusé
            {% endif %}
        </li>
         <li class="list-group-item"><span class="font-weight-bold">Bonus : </span>
            {% if station.bonus %}
                Oui
            {% else %}
                Non
            {% endif %}
        </li>
    </ul>
</div>
</div>
{% endwith %}
{% endblock %}

velouse/templates/velouse/station.html
{% extends "velose/base.html" %}

{% block title %}Station {{ station.number }} - {{ station.name }}{% endblock %}

{% load static %}
{% block css %} href="{% static 'velose/station_style.css' %}"{% endblock %}


{% block content %}

{% endblock %}